#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define N_CITIES 3
#define PASSENGER_QUEUE_SIZE 10

#define CUSTOM_SLEEP_SECS 3
#define INSPECTOR_SLEEP_SECS 2
#define TOURISTDOWLOADER_SLEEP_SECS 1
#define GETING_OFF_DELAY 1
#define GETING_ON_DELAY 0
#define MOORING_DELAY 0
#define MAX_WALKING_DELAY 3

#define LEGAL_SHIP_PROBABILITY 0.9
#define TOURIST_PROBABILITY 1
#define BUY_TICKET_PROBABILITY 0.75
#define PRECISION 100

#define CUSTOM_SIG 13
#define INSPECTION_SIG 14
#define TOURIST_SIG 15

#define IS_TOURIST 1
#define ISNT_TOURIST 0
#define HAS_TICKET 1
#define HASNT_TICKET 0
#define TRAVELING_FOWARD 1
#define TRAVELING_BACKWARD -1

#define MAX_ARG_SIZE 50
#define QUEUER_ARGS 6
#define SHIP_ARGS 3
#define SIGNALSENDER_ARGS 2
#define GENERATOR_ARGS 1

#endif /* CONSTANTS_H_ */
